//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverPaymentDetail
    {
        public long Id { get; set; }
        public string ClaimNumber { get; set; }
        public long MemberId { get; set; }
        public decimal BalanceAmt { get; set; }
        public decimal OverPaymentAmt { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime SysSrcSyncDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long OverPaymentID { get; set; }
    }
}
